[build-system]
requires = [
    "setuptools>=84.0.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "je_mail_thunder"
version = "0.0.28"
authors = [
    { name = "JE-Chen", email = "jechenmailman@gmail.com" },
]
description = ""
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICENSE"]
dependencies = []
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Development Status :: 2 - Pre-Alpha",
    "Environment :: Win32 (MS Windows)",
    "Environment :: MacOS X",
    "Environment :: X11 Applications",
    "Operating System :: OS Independent",
]

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.urls]
Homepage = "https://github.com/Integration-Automation/MailThunder"

[tool.setuptools.packages.find]
namespaces = false

[tool.pytest.ini_options]
testpaths = [
    "test",
]

[tool.bandit]
exclude_dirs = [
    "test",
]
skips = [
    "B101",
]
