version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  build-and-test-dev:
    executor: python/default
    steps:
      - checkout
      # pip require package
      - run:
          command: pip install --user -r dev_requirements.txt
          name: pip requirements.txt
      # content test
      - run:
          command: python ./test/unit_test/content/content_test.py
          name: content test

  build-and-test-stable:
    executor: python/default
    steps:
      - checkout
      # pip require package
      - run:
          command: pip install --user -r requirements.txt
          name: pip requirements.txt
      # content test
      - run:
          command: python ./test/unit_test/content/content_test.py
          name: content test

workflows:
  main:
    jobs:
      - build-and-test-dev
      - build-and-test-stable:
          requires:
            - build-and-test-dev
