version: 2.1

orbs:
  python: circleci/python@1.4.0

jobs:
  build-and-test-dev:
    executor: python/default
    steps:
      - checkout
      # pip require package
      - run:
          command: pip install --user -r dev_requirements.txt
          name: pip requirements.txt

  build-and-test-stable:
    executor: python/default
    steps:
      - checkout
      # pip require package
      - run:
          command: pip install --user -r requirements.txt
          name: pip requirements.txt

workflows:
  main:
    jobs:
      - build-and-test-dev
      - build-and-test-stable:
          requires:
            - build-and-test-dev
