name: MailThunder GitHub Actions Dev

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build_dev_version:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.5
      uses: actions/setup-python@v3
      with:
        python-version: "3.5"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r dev_requirements.txt
    - name: content test
      run: python ./test/unit_test/content/content_test.py