name: MailThunder GitHub Actions Stable

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build_stable_version:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.5
      uses: actions/setup-python@v3
      with:
        python-version: "3.5"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
    - name: content test
      run: python ./test/unit_test/content/content_test.py
    - name: argparse test
      run: python -m je_mail_thunder --user ${{ secrets.EMAIL_USER }}  --password   ${{ secrets.EMAIL_PASSWORD }}   --function send_mail --setting ${{ secrets.EMAIL_SETTING }}